### ISSUE TITLE
Add Grafana dashboard for the sandbox project with prometheus datasource

### ISSUE THREAD

**Issue by alhardy** [AppMetrics/Prometheus#2]

**Comment by alhardy** [comment]
Added grafana dashboard, few things missing/incorrect
- health gauges aren't reported
- apdex scores not reported (use prometheus functions instead?)
- error rate not calculated as rpm
- throughput / endpoint not consistent with other app metrics reporters?

**Comment by Rurouni** [comment]
- I have supported only Gauge,Counter,Meter,Historgram and Timer types
- Meters do not report rate, what they report is total count, then it's up to Grafana query to calculate rate via (https://prometheus.io/docs/querying/functions/#rate) . I think default is per sec everywhere in prometheus so it's up to query side to rescale
- I am transforming metrics names to adhere to Prometheus spec https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels  and guide https://prometheus.io/docs/practices/naming/ I am also lowercasing it which is not strictly in spec but I have noticed that all metrics in Kubernetes and various storages are lower case in prometheus so I though that it may be a thing.

**Comment by alhardy** [comment]
Cheers @Rurouni. Would you be able to fix the incorrect/missing queries in the grafana daahboard I've added by running the sandbox project in this repo.

**Comment by Rurouni** [comment]
I have fixed RPM queries in dashboard(it was about using *_count metric instead)
https://gist.github.com/Rurouni/c49fa744e4fff2f42578c5a37705ff70

Health and apdex still need to be added to reporter as gauges...

**Comment by Rurouni** [comment]
I have added those changes in this PR https://github.com/alhardy/AppMetrics.Extensions.Prometheus/pull/4
