### ISSUE TITLE
Metrics reset

### ISSUE THREAD

**Issue by CraigMellon** [AppMetrics/Prometheus#25]
Due to prometheus using a pull option rather than push what would be the best way to reset the metrics like we would on a push?

Has anyone implemented anything to that would maybe reset the metrics when the metrics endpoint is requested?

**Comment by Rurouni** [comment]
I wonder if Prometheus would handle it.  Majority of functions like rate() etc are supporting resets but they always explicitely mention the ones due to process restart. I don't think it's a good idea to reset it on every pull.
