### ISSUE TITLE
Throughput Metrics wrong

### ISSUE THREAD

**Issue by martinjt** [AppMetrics/Prometheus#26]
I'm trying to work out whether there is an issue with the app-metrics prometheus endpoint, or whether I'm just not understanding the way it's reporting things.  I completely understand that this could be a prometheus issue and you may not be able to help.

I'm using 
avg(rate(application_httprequests_transactions_count{env="$environment",app="$application",job="$job"}[1m])*60) by (rate)

There is a "server" dimension, which means I need to do the grouping.

However, every hour, there is a massive spike, to around 50x normal usage.  having checked network traffic manually, and all the load balancer traffic, we don't get this... 

My thought was that this could be some funkiness in maybe "resetting" the counts etc. inside the app-metrics stuff.

I'm at a loss right now, so any info from anyone who knows this stuff would be useful.  My currently action plan is try pushing to Influx at the same time, and then compare the results to work out if it's an app-metrics/prometheus specific thing or not.

**Comment by alhardy** [comment]
Related discussion: https://github.com/AppMetrics/Prometheus/issues/9#issuecomment-311095634

**Comment by alhardy** [comment]
Closing this as a duplicate to https://github.com/AppMetrics/Prometheus/issues/9#issuecomment-311095634 discussion can continue there.
