### ISSUE TITLE
Prometheus parsing error

### ISSUE THREAD

**Issue by davidrneves** [AppMetrics/Prometheus#39]
Hi,

I'm having trouble with parsing metrics in prometheus.
When I start prometheus, I get the following error:
**target=http://localhost:59404/metrics-text msg="append failed" err="invalid metric type "GAUGE"**

This probably has to do with the metric type being in upper case instead of lower case as prometheus expects: # TYPE application_httprequests_apdex **GAUGE**

After looking for the at the DataContract.cs for prometheus it seems that the enum MetricType is the culprit:

```csharp
    [global::ProtoBuf.ProtoContract(Name = @"MetricType")]
    public enum MetricType
    {

        [global::ProtoBuf.ProtoEnum(Name = @"COUNTER", Value = 0)]
        COUNTER = 0,

        [global::ProtoBuf.ProtoEnum(Name = @"GAUGE", Value = 1)]
        GAUGE = 1,

        [global::ProtoBuf.ProtoEnum(Name = @"SUMMARY", Value = 2)]
        SUMMARY = 2,

        [global::ProtoBuf.ProtoEnum(Name = @"UNTYPED", Value = 3)]
        UNTYPED = 3,

        [global::ProtoBuf.ProtoEnum(Name = @"HISTOGRAM", Value = 4)]
        HISTOGRAM = 4
    }
```

**Comment by Rurouni** [comment]
actually, that's something they introduced in 2.4.0  and Prometheus 2.3.2 still works with current format
