### ISSUE TITLE
As of Prometheus release 2.4 this formatter no longer functions.  Invalid metric type error for metric types containing capitals.

### ISSUE THREAD

**Issue by AbsorbJonny** [AppMetrics/Prometheus#40]
As of Prometheus release 2.4 this formatter no longer functions.  Prometheus ingestion of a metrics endpoint generated by this formatter causes the error "invalid metric type".  This seems to be due to the capitalization of characters in the comment text printed above the metric.

Example metric output that causes a failure:
```
# HELP process_memory_private_bytes
# TYPE process_memory_private_bytes GAUGE
process_memory_private_bytes 350601216
```
In the example above, the error generated by the Prometheus server is "invalid metric type "GAUGE"".  If this text is replaced with "gauge" no problem seems to occur.  This isn't #unique to App.Metrics, all client libraries need to be updated to conform to the breaking changes caused in release 2.4.  See the following:

https://github.com/prometheus-net/prometheus-net/issues/96
https://github.com/prometheus/prometheus/issues/4602

Thanks.

**Comment by tdabasinskas** [comment]
@alhardy, could you please look into this with some priority, as it makes the library completely unusable?

**Comment by alhardy** [comment]
@TDabasinskas I don't have much capacity at the moment, happy to take a PR in the meantime?

**Comment by tdabasinskas** [comment]
@alhardy, sure. Please see https://github.com/AppMetrics/Prometheus/pull/41.

**Comment by ben-foster-cko** [comment]
@alhardy did this get released? I'm still seeing uppercase metric types

**Comment by AbsorbJonny** [comment]
The fix was committed but no release was prepared.  👎   It appears others are discussing this same issue here:

https://github.com/AppMetrics/Prometheus/issues/23

**Comment by cryptiklemur** [comment]
@alhardy This still doesn't look to be released yet?

**Comment by alhardy** [comment]
Looks like the merge didn't apply for some reason.

Apologies, will look into this sometime this week

**Comment by Hyarmentir** [comment]
Hi @alhardy ,

any news on this fix ? 
I was really counting on it to update my prometheus installation. :)

**Comment by AbsorbJonny** [comment]
@Hyarmentir,

I just upgraded my packages to use the new version and the metric naming appears to be low-case as it should be.  I think this has been corrected.

**Comment by Hyarmentir** [comment]
@AbsorbJonny My bad, I have tested so much versions of app metrics and prometheus that I got mixed up.
I expected to have upper case metrics type, but you are right the purpose was to have them lower case now.
Thank you.
