### ISSUE TITLE
Prometheus doesn't like the feed produced by the AppMetrics API.

### ISSUE THREAD

**Issue by bdaniel7** [AppMetrics/Prometheus#49]
Prometheus doesn't like the feed produced by the AppMetrics API.
I'm configuring the AppMetrics like this:
```
public static IWebHostBuilder UseAppMetrics(this IWebHostBuilder webHostBuilder)
{
	return webHostBuilder.ConfigureMetricsWithDefaults((context, builder) =>
	{
		if (options.PrometheusEnabled)
		{
    		builder.OutputMetrics.AsPrometheusPlainText()
                    .OutputMetrics.AsPrometheusProtobuf();
		}
	}
	)
	.UseHealth()
	.UseHealthEndpoints()
	.UseMetricsWebTracking()
	.UseMetricsEndpoints((context, setup) =>
	{
		if (options.PrometheusEnabled)
	    {
		   setup.MetricsTextEndpointOutputFormatter = new 
                 MetricsPrometheusTextOutputFormatter();
		   setup.MetricsEndpointOutputFormatter = new 
                 MetricsPrometheusProtobufOutputFormatter();
		}
	})
   .UseMetrics();
}
```
When I visit the http://api.trains.online:5000/metrics, I see a json (that I attached to this issue).
[metrics.zip](https://github.com/AppMetrics/Prometheus/files/2874663/metrics.zip)

The Prometheus Targets page shows:

![prom-targets](https://user-images.githubusercontent.com/215914/52938410-480ef300-336a-11e9-99d1-2657cf68c2c0.png)

When I try the promtool, I get:
```
λ curl -s http://api.trains.online:5000/metrics | promtool check metrics
error while linting: text format parsing error in line 1: invalid metric name
```
So, how can I get some results in Prometheus?

**Comment by bdrupieski** [comment]
By default the metrics endpoints are /metrics and /metrics-text. /metrics will return JSON, and /metrics-text will return the Prometheus format. You need to use /metrics-text, not /metrics.

Also, you don't need to use both `MetricsPrometheusTextOutputFormatter` and `MetricsPrometheusProtobufOutputFormatter`. I recommend you only use `MetricsPrometheusTextOutputFormatter`. The protobuf format is no longer supported by Prometheus.

**Comment by bdaniel7** [comment]
I removed the MetricsPrometheusProtobufOutputFormatter.
I configured the job like this:

  - job_name: 'api'
    metrics_path: /metrics-text  
    static_configs:
      - targets: ['api.trains.online:5000']

But the endpoint is still not parsed:

strconv.ParseFloat: parsing "=": invalid syntax

λ curl -s http://api.trains.online:5000/metrics-text | promtool check metrics
error while linting: text format parsing error in line 4: expected float as value, got "="

**Comment by bdrupieski** [comment]
Can you post a zip of the output from your /metrics-text endpoint?

**Comment by bdaniel7** [comment]
It surely doesn't look like the output from the prometheus/metrics endpoint.
[metrics-text.zip](https://github.com/AppMetrics/Prometheus/files/2966529/metrics-text.zip)

**Comment by bdrupieski** [comment]
That's not the prometheus format. Are you sure you're using `MetricsPrometheusTextOutputFormatter`?

It should look something like this
```
# HELP http_apdex 
# TYPE http_apdex GAUGE
http_apdex{env="prod"} 0.92

# HELP http_active_requests 
# TYPE http_active_requests GAUGE
http_active_requests{env="prod"} 2

# HELP http_error_requests_total 
# TYPE http_error_requests_total COUNTER
http_error_requests_total{http_status_code="302",env="prod"} 8

http_error_requests_total{http_status_code="400",env="prod"} 548

http_error_requests_total{http_status_code="401",env="prod"} 1

http_error_requests_total{http_status_code="403",env="prod"} 377

http_error_requests_total{http_status_code="404",env="prod"} 26

http_error_requests_total{http_status_code="500",env="prod"} 11
```

**Comment by bdaniel7** [comment]
This is my configuration:

```
public static IWebHostBuilder UseAppMetrics(this IWebHostBuilder webHostBuilder)
		{
			return webHostBuilder.ConfigureMetricsWithDefaults(
				(context, builder) =>
					{
                       var options = context.Configuration.GetOptions<MetricsOptions>("metrics");
						if (!options.Enabled)
						{
							return;
						}

						if (options.PrometheusEnabled)
                        {
					        builder.OutputMetrics.AsPrometheusPlainText();
                        }  
					}
				)
				.UseHealth()
				.UseHealthEndpoints()
				.UseMetricsWebTracking()
				.UseMetricsEndpoints((context, setup) =>
				{
					setup.MetricsTextEndpointOutputFormatter = new 
                       MetricsPrometheusTextOutputFormatter();
				})
				.UseMetrics();
		}
```
And it's like this because I want to be able to switch on and off the collection of metrics.

**Comment by bdrupieski** [comment]
It looks like you're configuring the same thing multiple times. I don't believe you need all four `ConfigureMetricsWithDefaults`, `UseMetricsWebTracking`, `UseMetricsEndpoints`, and `UseMetrics`. I think you only need `UseMetrics` and can do the configuration on the `MetricsWebHostOptions` you can pass to it. It's not formatting the metrics in the Prometheus format because you're misconfiguring it here. 

By switch on and off the collection of metrics, do you mean on app startup, or on and off during runtime?

The way you're doing it means that you'll only change the format of how the endpoint is formatted. It won't change that an endpoint is exposed. Prometheus will also still try to scrape the endpoint. If you want to switch on and off whether the metrics are collected, you're probably better off configuring Prometheus somehow so it doesn't try to scrape the endpoint.

**Comment by bdaniel7** [comment]
By switch on/off, I meant to disable it for certain configurations.
But the metrics topic already had me waste many hours, so I'm giving up for now.
