### ISSUE TITLE
Reporting Metrics Measurement Type Incorrectly

### ISSUE THREAD

**Issue by ErikasKontenis** [AppMetrics/Prometheus#50]
Problem:
Prometheus reporting **Counter** measure type as a **Gauge** and **Histogram** as a **Summary**. During this measure type incorrect mapping can't use the specific recommended functions which are the best for example for the Counters instead for Gauges when creating dashboards in grafana.

Reproduction steps:
The reproduction can be easily made with the provided sample at https://github.com/AppMetrics/Samples.V2/tree/master/Net452.Metrics.Console.QuickStart

1. Download the Net452.Metrics.Console.QuickStart & install App.Metrics.Formatters.Prometheus Nuget
2. Replace the default OutputProvider to PrometheusOutputFormatter
Instead of 
`await metrics.DefaultOutputMetricsFormatter.WriteAsync(stream, snapshot);`
to
`await new MetricsPrometheusTextOutputFormatter().WriteAsync(stream, snapshot);`

For ex. the Counter metric
`metrics.Measure.Counter.Increment(new CounterOptions { Name = "my_counter" });`
Extected result should be:
`# TYPE application_my_counter caunter`
but instead it the output is:
`# TYPE application_my_counter gauge`

The same thing is for Histogram metric
`metrics.Measure.Histogram.Update(new HistogramOptions { Name = "my_histogram" }, 10);`
Expected result should be:
`# TYPE application_my_histogram histogram`
but instead it the output is:
`# TYPE application_my_histogram summary`

**Comment by bdrupieski** [comment]
This is expected. AppMetrics metric types do not map exactly to Prometheus metrics.

AppMetrics counters can go up and down. You can increment and decrement them. Prometheus counters only go up. Prometheus gauges can go up and down, so AppMetrics counters correspond to Prometheus gauges, not Prometheus counters.

This is how AppMetrics metric types map to Prometheus metric types:
```
Apdex     -> Gauge
Gauge     -> Gauge
Counter   -> Gauge
Meter     -> Counter
Histogram -> Summary
Timer     -> Summary
```

**Comment by ErikasKontenis** [comment]
OK, so all is clear now. Thank you @bdrupieski.
